module.exports = [
  "Gender",
  "Skin Tone",
  "Hair Color",
  "Hair Style",
  "Lipstick Type",
  "Lipstick Color",
  "Ear Stud Shape",
  "Ear Stud Gemstone",
  "Necklace Metal",
  "Necklace Gemstone",
  "Neck Chain",
  "Face",
  "Mouth",
  "Mood",
  "Eyeshadow",
  "Nerd Frame Type",
  "Nerd Frame Color",
  "Shades Type",
  "Shades Color",
  "3D Glasses",
  "VR Glasses",
  "Beard Shape",
  "Beard Color",
];
